// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: p2p_message_format.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmitShowInfoData_ShowInfoType int32

const (
	EmitShowInfoData_LOG_INFO   EmitShowInfoData_ShowInfoType = 0
	EmitShowInfoData_EVENT_INFO EmitShowInfoData_ShowInfoType = 1
)

// Enum value maps for EmitShowInfoData_ShowInfoType.
var (
	EmitShowInfoData_ShowInfoType_name = map[int32]string{
		0: "LOG_INFO",
		1: "EVENT_INFO",
	}
	EmitShowInfoData_ShowInfoType_value = map[string]int32{
		"LOG_INFO":   0,
		"EVENT_INFO": 1,
	}
)

func (x EmitShowInfoData_ShowInfoType) Enum() *EmitShowInfoData_ShowInfoType {
	p := new(EmitShowInfoData_ShowInfoType)
	*p = x
	return p
}

func (x EmitShowInfoData_ShowInfoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmitShowInfoData_ShowInfoType) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_message_format_proto_enumTypes[0].Descriptor()
}

func (EmitShowInfoData_ShowInfoType) Type() protoreflect.EnumType {
	return &file_p2p_message_format_proto_enumTypes[0]
}

func (x EmitShowInfoData_ShowInfoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmitShowInfoData_ShowInfoType.Descriptor instead.
func (EmitShowInfoData_ShowInfoType) EnumDescriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{11, 0}
}

type ChargingStatusData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Progress          float32 `protobuf:"fixed32,1,opt,name=progress,proto3" json:"progress,omitempty"`
	ChargingPeriod    string  `protobuf:"bytes,2,opt,name=charging_period,json=chargingPeriod,proto3" json:"charging_period,omitempty"`
	EnergyConsumption string  `protobuf:"bytes,3,opt,name=energy_consumption,json=energyConsumption,proto3" json:"energy_consumption,omitempty"`
	TokenSpent        string  `protobuf:"bytes,4,opt,name=token_spent,json=tokenSpent,proto3" json:"token_spent,omitempty"`
}

func (x *ChargingStatusData) Reset() {
	*x = ChargingStatusData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChargingStatusData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargingStatusData) ProtoMessage() {}

func (x *ChargingStatusData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargingStatusData.ProtoReflect.Descriptor instead.
func (*ChargingStatusData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{0}
}

func (x *ChargingStatusData) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ChargingStatusData) GetChargingPeriod() string {
	if x != nil {
		return x.ChargingPeriod
	}
	return ""
}

func (x *ChargingStatusData) GetEnergyConsumption() string {
	if x != nil {
		return x.EnergyConsumption
	}
	return ""
}

func (x *ChargingStatusData) GetTokenSpent() string {
	if x != nil {
		return x.TokenSpent
	}
	return ""
}

type ServiceAckData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *ServiceAckData) Reset() {
	*x = ServiceAckData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAckData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAckData) ProtoMessage() {}

func (x *ServiceAckData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAckData.ProtoReflect.Descriptor instead.
func (*ServiceAckData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceAckData) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

type ServiceRequestedAckData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *ServiceRequestedAckData) Reset() {
	*x = ServiceRequestedAckData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRequestedAckData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequestedAckData) ProtoMessage() {}

func (x *ServiceRequestedAckData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequestedAckData.ProtoReflect.Descriptor instead.
func (*ServiceRequestedAckData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceRequestedAckData) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

type ServiceRequestedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Consumer       string `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Provider       string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	TokenDeposited string `protobuf:"bytes,3,opt,name=token_deposited,json=tokenDeposited,proto3" json:"token_deposited,omitempty"`
	ConnectorId    int32  `protobuf:"varint,4,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
}

func (x *ServiceRequestedData) Reset() {
	*x = ServiceRequestedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRequestedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequestedData) ProtoMessage() {}

func (x *ServiceRequestedData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequestedData.ProtoReflect.Descriptor instead.
func (*ServiceRequestedData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceRequestedData) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *ServiceRequestedData) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ServiceRequestedData) GetTokenDeposited() string {
	if x != nil {
		return x.TokenDeposited
	}
	return ""
}

func (x *ServiceRequestedData) GetConnectorId() int32 {
	if x != nil {
		return x.ConnectorId
	}
	return 0
}

type ServiceDeliveredData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Consumer   string            `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Provider   string            `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	RefundInfo *TransactionValue `protobuf:"bytes,3,opt,name=refund_info,json=refundInfo,proto3" json:"refund_info,omitempty"`
	SpentInfo  *TransactionValue `protobuf:"bytes,4,opt,name=spent_info,json=spentInfo,proto3" json:"spent_info,omitempty"`
}

func (x *ServiceDeliveredData) Reset() {
	*x = ServiceDeliveredData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDeliveredData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDeliveredData) ProtoMessage() {}

func (x *ServiceDeliveredData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDeliveredData.ProtoReflect.Descriptor instead.
func (*ServiceDeliveredData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceDeliveredData) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *ServiceDeliveredData) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ServiceDeliveredData) GetRefundInfo() *TransactionValue {
	if x != nil {
		return x.RefundInfo
	}
	return nil
}

func (x *ServiceDeliveredData) GetSpentInfo() *TransactionValue {
	if x != nil {
		return x.SpentInfo
	}
	return nil
}

type StopChargeResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *StopChargeResponseData) Reset() {
	*x = StopChargeResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopChargeResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopChargeResponseData) ProtoMessage() {}

func (x *StopChargeResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopChargeResponseData.ProtoReflect.Descriptor instead.
func (*StopChargeResponseData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{5}
}

func (x *StopChargeResponseData) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

type IdentityChallengeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlainData string `protobuf:"bytes,1,opt,name=plain_data,json=plainData,proto3" json:"plain_data,omitempty"`
}

func (x *IdentityChallengeData) Reset() {
	*x = IdentityChallengeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityChallengeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityChallengeData) ProtoMessage() {}

func (x *IdentityChallengeData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityChallengeData.ProtoReflect.Descriptor instead.
func (*IdentityChallengeData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{6}
}

func (x *IdentityChallengeData) GetPlainData() string {
	if x != nil {
		return x.PlainData
	}
	return ""
}

type IdentityResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp      *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Signature string    `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *IdentityResponseData) Reset() {
	*x = IdentityResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResponseData) ProtoMessage() {}

func (x *IdentityResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResponseData.ProtoReflect.Descriptor instead.
func (*IdentityResponseData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{7}
}

func (x *IdentityResponseData) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *IdentityResponseData) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{8}
}

func (x *Response) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TransactionValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenNum  string                      `protobuf:"bytes,1,opt,name=token_num,json=tokenNum,proto3" json:"token_num,omitempty"`
	TxHash    string                      `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TimePoint *TransactionValue_TimePoint `protobuf:"bytes,3,opt,name=time_point,json=timePoint,proto3" json:"time_point,omitempty"`
	CallHash  string                      `protobuf:"bytes,4,opt,name=call_hash,json=callHash,proto3" json:"call_hash,omitempty"`
}

func (x *TransactionValue) Reset() {
	*x = TransactionValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionValue) ProtoMessage() {}

func (x *TransactionValue) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionValue.ProtoReflect.Descriptor instead.
func (*TransactionValue) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionValue) GetTokenNum() string {
	if x != nil {
		return x.TokenNum
	}
	return ""
}

func (x *TransactionValue) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionValue) GetTimePoint() *TransactionValue_TimePoint {
	if x != nil {
		return x.TimePoint
	}
	return nil
}

func (x *TransactionValue) GetCallHash() string {
	if x != nil {
		return x.CallHash
	}
	return ""
}

type ChainEventData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId    string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Attributes string `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *ChainEventData) Reset() {
	*x = ChainEventData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChainEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainEventData) ProtoMessage() {}

func (x *ChainEventData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainEventData.ProtoReflect.Descriptor instead.
func (*ChainEventData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{10}
}

func (x *ChainEventData) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ChainEventData) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

type EmitShowInfoData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type EmitShowInfoData_ShowInfoType `protobuf:"varint,1,opt,name=type,proto3,enum=p2p.EmitShowInfoData_ShowInfoType" json:"type,omitempty"`
	Data string                        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EmitShowInfoData) Reset() {
	*x = EmitShowInfoData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitShowInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitShowInfoData) ProtoMessage() {}

func (x *EmitShowInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitShowInfoData.ProtoReflect.Descriptor instead.
func (*EmitShowInfoData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{11}
}

func (x *EmitShowInfoData) GetType() EmitShowInfoData_ShowInfoType {
	if x != nil {
		return x.Type
	}
	return EmitShowInfoData_LOG_INFO
}

func (x *EmitShowInfoData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetBalanceAckData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp    *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Balance string    `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *GetBalanceAckData) Reset() {
	*x = GetBalanceAckData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceAckData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceAckData) ProtoMessage() {}

func (x *GetBalanceAckData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceAckData.ProtoReflect.Descriptor instead.
func (*GetBalanceAckData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{12}
}

func (x *GetBalanceAckData) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetBalanceAckData) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type GetPKAckData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Pk   string    `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
}

func (x *GetPKAckData) Reset() {
	*x = GetPKAckData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPKAckData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPKAckData) ProtoMessage() {}

func (x *GetPKAckData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPKAckData.ProtoReflect.Descriptor instead.
func (*GetPKAckData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{13}
}

func (x *GetPKAckData) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetPKAckData) GetPk() string {
	if x != nil {
		return x.Pk
	}
	return ""
}

type RePublishDIDAckData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Pk   string    `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
}

func (x *RePublishDIDAckData) Reset() {
	*x = RePublishDIDAckData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RePublishDIDAckData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RePublishDIDAckData) ProtoMessage() {}

func (x *RePublishDIDAckData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RePublishDIDAckData.ProtoReflect.Descriptor instead.
func (*RePublishDIDAckData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{14}
}

func (x *RePublishDIDAckData) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *RePublishDIDAckData) GetPk() string {
	if x != nil {
		return x.Pk
	}
	return ""
}

type ReconnectAckData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp    *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReconnectAckData) Reset() {
	*x = ReconnectAckData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconnectAckData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectAckData) ProtoMessage() {}

func (x *ReconnectAckData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectAckData.ProtoReflect.Descriptor instead.
func (*ReconnectAckData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{15}
}

func (x *ReconnectAckData) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *ReconnectAckData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopChargeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *StopChargeData) Reset() {
	*x = StopChargeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopChargeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopChargeData) ProtoMessage() {}

func (x *StopChargeData) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopChargeData.ProtoReflect.Descriptor instead.
func (*StopChargeData) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{16}
}

func (x *StopChargeData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TransactionValue_TimePoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Index  int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *TransactionValue_TimePoint) Reset() {
	*x = TransactionValue_TimePoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_message_format_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionValue_TimePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionValue_TimePoint) ProtoMessage() {}

func (x *TransactionValue_TimePoint) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_message_format_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionValue_TimePoint.ProtoReflect.Descriptor instead.
func (*TransactionValue_TimePoint) Descriptor() ([]byte, []int) {
	return file_p2p_message_format_proto_rawDescGZIP(), []int{9, 0}
}

func (x *TransactionValue_TimePoint) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TransactionValue_TimePoint) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_p2p_message_format_proto protoreflect.FileDescriptor

var file_p2p_message_format_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x32, 0x70, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x32, 0x70, 0x22,
	0xa9, 0x01, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x67, 0x5f, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x68, 0x61,
	0x72, 0x67, 0x69, 0x6e, 0x67, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x65,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x5f, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x22, 0x33, 0x0a, 0x0e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a,
	0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x32,
	0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70,
	0x22, 0x3c, 0x0a, 0x17, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x41, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x04, 0x72,
	0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x32, 0x70, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22, 0x9a,
	0x01, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12,
	0x27, 0x0a, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x14,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x0b,
	0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x0a, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x09, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3b, 0x0a, 0x16, 0x53, 0x74,
	0x6f, 0x70, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22, 0x36, 0x0a, 0x15, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x57, 0x0a, 0x14, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x3a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xe0, 0x01, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x4e, 0x75, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x3e, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x39, 0x0a, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x4b, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x10, 0x45, 0x6d, 0x69, 0x74, 0x53, 0x68, 0x6f,
	0x77, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x45, 0x6d,
	0x69, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x53,
	0x68, 0x6f, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x77, 0x49, 0x6e, 0x66,
	0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x4f, 0x47, 0x5f, 0x49, 0x4e, 0x46,
	0x4f, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x49, 0x4e, 0x46,
	0x4f, 0x10, 0x01, 0x22, 0x50, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x41, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x4b, 0x41, 0x63,
	0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x6b, 0x22, 0x48, 0x0a, 0x13, 0x52, 0x65, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x49, 0x44, 0x41, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x21, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x32, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x72, 0x65,
	0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x70, 0x6b, 0x22, 0x4f, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41,
	0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42,
	0x57, 0x5a, 0x55, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65,
	0x61, 0x71, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x65, 0x61, 0x71, 0x2d, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2d, 0x65, 0x76, 0x2d, 0x63, 0x68, 0x61, 0x72, 0x67, 0x69,
	0x6e, 0x67, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2d, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_p2p_message_format_proto_rawDescOnce sync.Once
	file_p2p_message_format_proto_rawDescData = file_p2p_message_format_proto_rawDesc
)

func file_p2p_message_format_proto_rawDescGZIP() []byte {
	file_p2p_message_format_proto_rawDescOnce.Do(func() {
		file_p2p_message_format_proto_rawDescData = protoimpl.X.CompressGZIP(file_p2p_message_format_proto_rawDescData)
	})
	return file_p2p_message_format_proto_rawDescData
}

var file_p2p_message_format_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_p2p_message_format_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_p2p_message_format_proto_goTypes = []interface{}{
	(EmitShowInfoData_ShowInfoType)(0), // 0: p2p.EmitShowInfoData.ShowInfoType
	(*ChargingStatusData)(nil),         // 1: p2p.ChargingStatusData
	(*ServiceAckData)(nil),             // 2: p2p.ServiceAckData
	(*ServiceRequestedAckData)(nil),    // 3: p2p.ServiceRequestedAckData
	(*ServiceRequestedData)(nil),       // 4: p2p.ServiceRequestedData
	(*ServiceDeliveredData)(nil),       // 5: p2p.ServiceDeliveredData
	(*StopChargeResponseData)(nil),     // 6: p2p.StopChargeResponseData
	(*IdentityChallengeData)(nil),      // 7: p2p.IdentityChallengeData
	(*IdentityResponseData)(nil),       // 8: p2p.IdentityResponseData
	(*Response)(nil),                   // 9: p2p.Response
	(*TransactionValue)(nil),           // 10: p2p.TransactionValue
	(*ChainEventData)(nil),             // 11: p2p.ChainEventData
	(*EmitShowInfoData)(nil),           // 12: p2p.EmitShowInfoData
	(*GetBalanceAckData)(nil),          // 13: p2p.GetBalanceAckData
	(*GetPKAckData)(nil),               // 14: p2p.GetPKAckData
	(*RePublishDIDAckData)(nil),        // 15: p2p.RePublishDIDAckData
	(*ReconnectAckData)(nil),           // 16: p2p.ReconnectAckData
	(*StopChargeData)(nil),             // 17: p2p.StopChargeData
	(*TransactionValue_TimePoint)(nil), // 18: p2p.TransactionValue.TimePoint
}
var file_p2p_message_format_proto_depIdxs = []int32{
	9,  // 0: p2p.ServiceAckData.resp:type_name -> p2p.Response
	9,  // 1: p2p.ServiceRequestedAckData.resp:type_name -> p2p.Response
	10, // 2: p2p.ServiceDeliveredData.refund_info:type_name -> p2p.TransactionValue
	10, // 3: p2p.ServiceDeliveredData.spent_info:type_name -> p2p.TransactionValue
	9,  // 4: p2p.StopChargeResponseData.resp:type_name -> p2p.Response
	9,  // 5: p2p.IdentityResponseData.resp:type_name -> p2p.Response
	18, // 6: p2p.TransactionValue.time_point:type_name -> p2p.TransactionValue.TimePoint
	0,  // 7: p2p.EmitShowInfoData.type:type_name -> p2p.EmitShowInfoData.ShowInfoType
	9,  // 8: p2p.GetBalanceAckData.resp:type_name -> p2p.Response
	9,  // 9: p2p.GetPKAckData.resp:type_name -> p2p.Response
	9,  // 10: p2p.RePublishDIDAckData.resp:type_name -> p2p.Response
	9,  // 11: p2p.ReconnectAckData.resp:type_name -> p2p.Response
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_p2p_message_format_proto_init() }
func file_p2p_message_format_proto_init() {
	if File_p2p_message_format_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_p2p_message_format_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChargingStatusData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceAckData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRequestedAckData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRequestedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDeliveredData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopChargeResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityChallengeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChainEventData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitShowInfoData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceAckData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPKAckData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RePublishDIDAckData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconnectAckData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopChargeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_message_format_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionValue_TimePoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p2p_message_format_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_message_format_proto_goTypes,
		DependencyIndexes: file_p2p_message_format_proto_depIdxs,
		EnumInfos:         file_p2p_message_format_proto_enumTypes,
		MessageInfos:      file_p2p_message_format_proto_msgTypes,
	}.Build()
	File_p2p_message_format_proto = out.File
	file_p2p_message_format_proto_rawDesc = nil
	file_p2p_message_format_proto_goTypes = nil
	file_p2p_message_format_proto_depIdxs = nil
}
